# Generated by Django 5.2.3 on 2025-07-01 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('investor_id', models.AutoField(primary_key=True, serialize=False)),
                ('founder', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('descr', models.TextField(blank=True, null=True)),
                ('net_worth', models.PositiveIntegerField()),
                ('contact_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'Investor',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Sector',
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('startup_id', models.AutoField(primary_key=True, serialize=False)),
                ('startup_name', models.CharField(max_length=100)),
                ('descr', models.TextField()),
                ('founder', models.CharField(max_length=100)),
                ('valuation', models.PositiveIntegerField()),
                ('last_year_profit', models.IntegerField(blank=True, null=True)),
                ('burn_rate', models.FloatField(blank=True, null=True)),
                ('contact_no', models.CharField(max_length=13)),
                ('email_id', models.EmailField(max_length=50)),
                ('sector', models.ForeignKey(db_column='sector', on_delete=django.db.models.deletion.CASCADE, to='startup_app.sector')),
            ],
            options={
                'db_table': 'Startup',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('investment_asked', models.PositiveIntegerField(default=0)),
                ('equity_offered', models.FloatField(default=0.0)),
                ('loan_req', models.PositiveIntegerField(default=0)),
                ('loan_rate', models.FloatField(default=0.0)),
                ('loan_time', models.PositiveIntegerField(default=12)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_app.startup')),
            ],
            options={
                'db_table': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('deal_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_deal', models.DateField()),
                ('amount_invested', models.PositiveIntegerField(default=0)),
                ('loan_given', models.PositiveIntegerField(default=0)),
                ('loan_time', models.PositiveIntegerField(default=0)),
                ('loan_rate', models.FloatField(default=0.0)),
                ('equity', models.FloatField(default=0.0)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_app.investor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_app.startup')),
            ],
            options={
                'db_table': 'Deals',
            },
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.FloatField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_app.investor')),
                ('sector', models.ForeignKey(db_column='sector_name', on_delete=django.db.models.deletion.CASCADE, to='startup_app.sector')),
            ],
            options={
                'db_table': 'Choices',
                'unique_together': {('investor', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startup_app.investor')),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startup_app.startup')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('investor__isnull', False), ('startup__isnull', False), _connector='OR'), name='investor_or_startup_not_null')],
            },
        ),
    ]
