# Generated by Django 5.2.3 on 2025-07-01 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='investor',
            field=models.ForeignKey(blank=True, db_column='investor_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='startup_app.investor'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='startup',
            field=models.ForeignKey(blank=True, db_column='startup_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='startup_app.startup'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(db_column='username', max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='appuser',
            table='user',
        ),
    ]
