# Generated by Django 5.2.3 on 2025-07-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_app', '0002_alter_choices_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
        migrations.AlterField(
            model_name='deals',
            name='amount_invested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deals',
            name='date_of_deal',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deals',
            name='loan_given',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deals',
            name='loan_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investor',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='investor',
            name='net_worth',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='offers',
            name='investment_asked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offers',
            name='loan_req',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offers',
            name='loan_time',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='startup',
            name='email_id',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='startup',
            name='valuation',
            field=models.PositiveIntegerField(),
        ),
    ]
