# Generated by Django 5.2.3 on 2025-07-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup_app', '0003_rename_user_appuser_alter_deals_amount_invested_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='startup',
            table='startup',
        ),
    ]
